improve remove volumes logic

diff --git a/docker-gc b/docker-gc
--- a/docker-gc
+++ b/docker-gc
@@ -304,19 +304,23 @@ else
     xargs -n 1 $DOCKER rmi $FORCE_IMAGE_FLAG < images.reap &>/dev/null || true
 fi
 
-if [[ $REMOVE_VOLUMES -gt 0]]; then
-    # Find all volumes
-    $DOCKER volume ls -q > volumes.all
-
-    # Find all  volumes that are in use
-    $DOCKER inspect --format="{{range .Mounts}}{{.Name}}{{end}}" $($DOCKER ps -aq) | sed '/^$/d' > volumes.used
-
-    comm -23 volumes.all volumes.used > volumes.reap
-
-    if [[ $DRY_RUN -gt 0 ]]; then
-        volumes_log "The following volume would have been removed" volumes.reap
+if [[ $REMOVE_VOLUMES -gt 0 ]]; then
+    set +e
+    $DOCKER volume ls --filter "dangling=true" -q &> /dev/null
+    VOLUMES=$?
+    set -e
+    # If docker volume ls fails, then is probably not supported by either client or server
+    if [[ $VOLUMES -gt 0 ]]; then
+        MESSAGE="Removing volumes is not supported for for docker version "$($DOCKER version --format="Client: {{.Client.Version}} Server: {{.Server.Version}}")
+        log "$MESSAGE"
     else
-        volumes_log "Removing volume" volumes.reap
-        xargs -n 1 $DOCKER rm < volumes.reap &>/dev/null || true
+        $DOCKER volume ls --filter "dangling=true" -q > volumes.reap
+
+        if [[ $DRY_RUN -gt 0 ]]; then
+            volumes_log "The following volume would have been removed" volumes.reap
+        else
+            volumes_log "Removing volume" volumes.reap
+            xargs -n 1 $DOCKER volume rm < volumes.reap &>/dev/null || true
+        fi
     fi
 fi
