Maintain consistent indentation to 2 space

diff --git a/docker-gc b/docker-gc
--- a/docker-gc
+++ b/docker-gc
@@ -98,102 +98,102 @@ function date_parse() {
 
 # Elapsed time since a docker timestamp, in seconds
 function elapsed_time() {
-    # Docker 1.5.0 datetime format is 2015-07-03T02:39:00.390284991
-    # Docker 1.7.0 datetime format is 2015-07-03 02:39:00.390284991 +0000 UTC
-    utcnow=$(date -u "+%s")
-    replace_q="${1#\"}"
-    without_ms="${replace_q:0:19}"
-    replace_t="${without_ms/T/ }"
-    epoch=$(date_parse "${replace_t}")
-    echo $(($utcnow - $epoch))
+  # Docker 1.5.0 datetime format is 2015-07-03T02:39:00.390284991
+  # Docker 1.7.0 datetime format is 2015-07-03 02:39:00.390284991 +0000 UTC
+  utcnow=$(date -u "+%s")
+  replace_q="${1#\"}"
+  without_ms="${replace_q:0:19}"
+  replace_t="${without_ms/T/ }"
+  epoch=$(date_parse "${replace_t}")
+  echo $(($utcnow - $epoch))
 }
 
 function compute_exclude_ids() {
-    # Find images that match patterns in the EXCLUDE_FROM_GC file and put their
-    # id prefixes into $EXCLUDE_IDS_FILE, prefixed with ^
+  # Find images that match patterns in the EXCLUDE_FROM_GC file and put their
+  # id prefixes into $EXCLUDE_IDS_FILE, prefixed with ^
 
-    PROCESSED_EXCLUDES="processed_excludes.tmp"
-    # Take each line and put a space at the beginning and end, so when we
-    # grep for them below, it will effectively be: "match either repo:tag
-    # or imageid".  Also delete blank lines or lines that only contain
-    # whitespace
-    sed 's/^\(.*\)$/ \1 /' $EXCLUDE_FROM_GC | sed '/^ *$/d' > $PROCESSED_EXCLUDES
-    # The following looks a bit of a mess, but here's what it does:
-    # 1. Get images
-    # 2. Skip header line
-    # 3. Turn columnar display of 'REPO TAG IMAGEID ....' to 'REPO:TAG IMAGEID'
-    # 4. find lines that contain things mentioned in PROCESSED_EXCLUDES
-    # 5. Grab the image id from the line
-    # 6. Prepend ^ to the beginning of each line
+  PROCESSED_EXCLUDES="processed_excludes.tmp"
+  # Take each line and put a space at the beginning and end, so when we
+  # grep for them below, it will effectively be: "match either repo:tag
+  # or imageid".  Also delete blank lines or lines that only contain
+  # whitespace
+  sed 's/^\(.*\)$/ \1 /' $EXCLUDE_FROM_GC | sed '/^ *$/d' > $PROCESSED_EXCLUDES
+  # The following looks a bit of a mess, but here's what it does:
+  # 1. Get images
+  # 2. Skip header line
+  # 3. Turn columnar display of 'REPO TAG IMAGEID ....' to 'REPO:TAG IMAGEID'
+  # 4. find lines that contain things mentioned in PROCESSED_EXCLUDES
+  # 5. Grab the image id from the line
+  # 6. Prepend ^ to the beginning of each line
 
-    # What this does is make grep patterns to match image ids mentioned by
-    # either repo:tag or image id for later greppage
-    $DOCKER images \
-        | tail -n+2 \
-        | sed 's/^\([^ ]*\) *\([^ ]*\) *\([^ ]*\).*/ \1:\2 \3 /' \
-        | grep -f $PROCESSED_EXCLUDES 2>/dev/null \
-        | cut -d' ' -f3 \
-        | sed 's/^/^(sha256:)?/' > $EXCLUDE_IDS_FILE
+  # What this does is make grep patterns to match image ids mentioned by
+  # either repo:tag or image id for later greppage
+  $DOCKER images \
+    | tail -n+2 \
+    | sed 's/^\([^ ]*\) *\([^ ]*\) *\([^ ]*\).*/ \1:\2 \3 /' \
+    | grep -f $PROCESSED_EXCLUDES 2>/dev/null \
+    | cut -d' ' -f3 \
+    | sed 's/^/^(sha256:)?/' > $EXCLUDE_IDS_FILE
 }
 
 function compute_exclude_container_ids() {
-    # Find containers matching to patterns listed in EXCLUDE_CONTAINERS_FROM_GC file
-    # Implode their values with a \| separator on a single line
-    PROCESSED_EXCLUDES=`cat $EXCLUDE_CONTAINERS_FROM_GC \
-        | xargs \
-        | sed -e 's/ /\|/g'`
-    # The empty string would match everything
-    if [ "$PROCESSED_EXCLUDES" = "" ]; then
-        touch $EXCLUDE_CONTAINER_IDS_FILE
-        return
-    fi
-    # Find all docker images
-    # Filter out with matching names
-    # and put them to $EXCLUDE_CONTAINER_IDS_FILE
-    $DOCKER ps -a \
-        | grep -E "$PROCESSED_EXCLUDES" \
-        | awk '{ print $1 }' \
-        | tr -s " " "\012" \
-        | sort -u > $EXCLUDE_CONTAINER_IDS_FILE
+  # Find containers matching to patterns listed in EXCLUDE_CONTAINERS_FROM_GC file
+  # Implode their values with a \| separator on a single line
+  PROCESSED_EXCLUDES=`cat $EXCLUDE_CONTAINERS_FROM_GC \
+    | xargs \
+    | sed -e 's/ /\|/g'`
+  # The empty string would match everything
+  if [ "$PROCESSED_EXCLUDES" = "" ]; then
+    touch $EXCLUDE_CONTAINER_IDS_FILE
+    return
+  fi
+  # Find all docker images
+  # Filter out with matching names
+  # and put them to $EXCLUDE_CONTAINER_IDS_FILE
+  $DOCKER ps -a \
+    | grep -E "$PROCESSED_EXCLUDES" \
+    | awk '{ print $1 }' \
+    | tr -s " " "\012" \
+    | sort -u > $EXCLUDE_CONTAINER_IDS_FILE
 }
 
 function log() {
-    msg=$1
-    if [[ $LOG_TO_SYSLOG -gt 0 ]]; then
-        logger -i -t "$SYSLOG_TAG" -p "$SYSLOG_FACILITY.$SYSLOG_LEVEL" "$msg"
-    else
-        echo "[$(date +'%Y-%m-%dT%H:%M:%S')] [INFO] : $msg"
-    fi
+  msg=$1
+  if [[ $LOG_TO_SYSLOG -gt 0 ]]; then
+    logger -i -t "$SYSLOG_TAG" -p "$SYSLOG_FACILITY.$SYSLOG_LEVEL" "$msg"
+  else
+    echo "[$(date +'%Y-%m-%dT%H:%M:%S')] [INFO] : $msg"
+  fi
 }
 
 function container_log() {
-    prefix=$1
-    filename=$2
+  prefix=$1
+  filename=$2
 
-    while IFS='' read -r containerid
-    do
-        log "$prefix $containerid $(${DOCKER} inspect -f {{.Name}} $containerid)"
-    done < "$filename"
+  while IFS='' read -r containerid
+  do
+    log "$prefix $containerid $(${DOCKER} inspect -f {{.Name}} $containerid)"
+  done < "$filename"
 }
 
 function image_log() {
-    prefix=$1
-    filename=$2
+  prefix=$1
+  filename=$2
 
-    while IFS='' read -r imageid
-    do
-        log "$prefix $imageid $(${DOCKER} inspect -f {{.RepoTags}} $imageid)"
-    done < "$filename"
+  while IFS='' read -r imageid
+  do
+    log "$prefix $imageid $(${DOCKER} inspect -f {{.RepoTags}} $imageid)"
+  done < "$filename"
 }
 
 function volumes_log() {
-    prefix=$1
-    filename=$2
+  prefix=$1
+  filename=$2
 
-    while IFS='' read -r volumeid
-    do
-        log "$prefix $volumeid"
-    done < "$filename"
+  while IFS='' read -r volumeid
+  do
+    log "$prefix $volumeid"
+  done < "$filename"
 }
 
 # Change into the state directory (and create it if it doesn't exist)
@@ -223,11 +223,11 @@ compute_exclude_container_ids
 comm -23 containers.all containers.running > containers.exited
 
 if [[ $EXCLUDE_DEAD -gt 0 ]]; then
-    echo "Excluding dead containers"
-    # List dead containers
-    $DOCKER ps -q -a -f status=dead | sort | uniq > containers.dead
-    comm -23 containers.exited containers.dead > containers.exited.tmp
-    cat containers.exited.tmp > containers.exited
+  echo "Excluding dead containers"
+  # List dead containers
+  $DOCKER ps -q -a -f status=dead | sort | uniq > containers.dead
+  comm -23 containers.exited containers.dead > containers.exited.tmp
+  cat containers.exited.tmp > containers.exited
 fi
 
 container_log "Container not running" containers.exited
@@ -236,11 +236,11 @@ container_log "Container not running" containers.exited
 > containers.reap.tmp
 cat containers.exited | while read line
 do
-    EXITED=$(${DOCKER} inspect -f "{{json .State.FinishedAt}}" ${line})
-    ELAPSED=$(elapsed_time $EXITED)
-    if [[ $ELAPSED -gt $GRACE_PERIOD_SECONDS ]]; then
-        echo $line >> containers.reap.tmp
-    fi
+  EXITED=$(${DOCKER} inspect -f "{{json .State.FinishedAt}}" ${line})
+  ELAPSED=$(elapsed_time $EXITED)
+  if [[ $ELAPSED -gt $GRACE_PERIOD_SECONDS ]]; then
+    echo $line >> containers.reap.tmp
+  fi
 done
 
 # List containers that we will remove and exclude ids.
@@ -258,7 +258,7 @@ sort | uniq > images.used
 echo -n "" > images.all
 $DOCKER images | while read line
 do
-    awk '{print $1};'
+  awk '{print $1};'
 done | sort | uniq | while read line
 do
   $DOCKER images --no-trunc --format "{{.ID}} {{.CreatedAt}}" $line \
@@ -275,18 +275,18 @@ $DOCKER images --no-trunc --format "{{.ID}}" --filter dangling=true >> images.al
 > images.reap.tmp
 cat images.all | sort | uniq | while read line
 do
-    # the `docker inspect` command might fail sometimes due to issues like
-    # https://github.com/moby/moby/issues/35747 - don't let that abort this script
-    set +o errexit
-    CREATED=$(${DOCKER} inspect -f "{{.Created}}" ${line})
-    retval=$?
-    set -o errexit
-    if [ $retval -eq 0 ]; then
-        ELAPSED=$(elapsed_time $CREATED)
-        if [[ $ELAPSED -gt $GRACE_PERIOD_SECONDS ]]; then
-            echo $line >> images.reap.tmp
-        fi
+  # the `docker inspect` command might fail sometimes due to issues like
+  # https://github.com/moby/moby/issues/35747 - don't let that abort this script
+  set +o errexit
+  CREATED=$(${DOCKER} inspect -f "{{.Created}}" ${line})
+  retval=$?
+  set -o errexit
+  if [ $retval -eq 0 ]; then
+    ELAPSED=$(elapsed_time $CREATED)
+    if [[ $ELAPSED -gt $GRACE_PERIOD_SECONDS ]]; then
+      echo $line >> images.reap.tmp
     fi
+  fi
 done
 comm -23 images.reap.tmp images.used | grep -E -v -f $EXCLUDE_IDS_FILE > images.reap || true
 
@@ -294,73 +294,73 @@ comm -23 images.reap.tmp images.used | grep -E -v -f $EXCLUDE_IDS_FILE > images.
 # status or give errors when removing.
 FORCE_CONTAINER_FLAG=""
 if [[ $FORCE_CONTAINER_REMOVAL -gt 0 ]]; then
-    FORCE_CONTAINER_FLAG="-f"
+  FORCE_CONTAINER_FLAG="-f"
 fi
 
 # Remove associated volume, so that we won't create new orphan volumes.
 if [[ $REMOVE_ASSOCIATED_VOLUME -gt 0 ]]; then
-    if [[ -z $FORCE_CONTAINER_FLAG ]]; then
-        FORCE_CONTAINER_FLAG="-v"
-    else
-        FORCE_CONTAINER_FLAG=$FORCE_CONTAINER_FLAG"v"
-    fi
+  if [[ -z $FORCE_CONTAINER_FLAG ]]; then
+    FORCE_CONTAINER_FLAG="-v"
+  else
+    FORCE_CONTAINER_FLAG=$FORCE_CONTAINER_FLAG"v"
+  fi
 fi
 # Reap containers.
 if [[ $DRY_RUN -gt 0 ]]; then
-    container_log "The following container would have been removed" containers.reap
+  container_log "The following container would have been removed" containers.reap
 else
-    container_log "Removing containers" containers.reap
-    xargs -n 1 $DOCKER rm $FORCE_CONTAINER_FLAG --volumes=true < containers.reap &>/dev/null || true
+  container_log "Removing containers" containers.reap
+  xargs -n 1 $DOCKER rm $FORCE_CONTAINER_FLAG --volumes=true < containers.reap &>/dev/null || true
 fi
 
 # Use -f flag on docker rmi command; forces removal of images that have multiple tags
 FORCE_IMAGE_FLAG=""
 if [[ $FORCE_IMAGE_REMOVAL -gt 0 ]]; then
-    FORCE_IMAGE_FLAG="-f"
+  FORCE_IMAGE_FLAG="-f"
 fi
 
 # Reap images.
 if [[ $DRY_RUN -gt 0 ]]; then
-    image_log "The following image would have been removed" images.reap
+  image_log "The following image would have been removed" images.reap
 else
-    image_log "Removing image" images.reap
-    xargs -n 1 $DOCKER rmi $FORCE_IMAGE_FLAG < images.reap &>/dev/null || true
+  image_log "Removing image" images.reap
+  xargs -n 1 $DOCKER rmi $FORCE_IMAGE_FLAG < images.reap &>/dev/null || true
 fi
 
 if [[ $REMOVE_VOLUMES -gt 0 ]]; then
+  set +e
+  $DOCKER volume ls --filter "dangling=true" -q &> /dev/null
+  VOLUMES=$?
+  set -e
+  # If docker volume ls fails, then is probably not supported by either client or server
+  if [ ! -f "$EXCLUDE_VOLUMES_IDS_FILE" ]
+  then
+    EXCLUDE_VOLUMES_IDS_FILE=/dev/null
+  fi
+
+  if [[ $VOLUMES -gt 0 ]]; then
     set +e
-    $DOCKER volume ls --filter "dangling=true" -q &> /dev/null
-    VOLUMES=$?
+    VERSION=$($DOCKER version --format="Client: {{.Client.Version}} Server: {{.Server.Version}}" 2&>/dev/null)
+    FORMAT=$?
     set -e
-    # If docker volume ls fails, then is probably not supported by either client or server
-    if [ ! -f "$EXCLUDE_VOLUMES_IDS_FILE" ]
-    then
-        EXCLUDE_VOLUMES_IDS_FILE=/dev/null
-    fi
-
-    if [[ $VOLUMES -gt 0 ]]; then
-        set +e
-        VERSION=$($DOCKER version --format="Client: {{.Client.Version}} Server: {{.Server.Version}}" 2&>/dev/null)
-        FORMAT=$?
-        set -e
-        if [[ $FORMAT -gt 0 ]]; then
-            log "Removing volumes is not supported for Docker < 1.9.0"
-        else
-            MESSAGE="Removing volumes is not supported for for docker version "$($DOCKER version --format="Client: {{.Client.Version}} Server: {{.Server.Version}}") &
-            log "$MESSAGE"
-        fi
+    if [[ $FORMAT -gt 0 ]]; then
+      log "Removing volumes is not supported for Docker < 1.9.0"
     else
-        if [[ -z "$VOLUME_DELETE_ONLY_DRIVER" ]]; then
-            $DOCKER volume ls --filter "dangling=true" -q | grep -v -f $EXCLUDE_VOLUMES_IDS_FILE > volumes.reap || true
-        else
-            $DOCKER volume ls --filter "dangling=true" --filter "driver=$VOLUME_DELETE_ONLY_DRIVER" -q | grep -v -f $EXCLUDE_VOLUMES_IDS_FILE > volumes.reap || true
-        fi
-
-        if [[ $DRY_RUN -gt 0 ]]; then
-            volumes_log "The following volume would have been removed" volumes.reap
-        else
-            volumes_log "Removing volume" volumes.reap
-            xargs -n 1 $DOCKER volume rm < volumes.reap &>/dev/null || true
-        fi
+      MESSAGE="Removing volumes is not supported for for docker version "$($DOCKER version --format="Client: {{.Client.Version}} Server: {{.Server.Version}}") &
+      log "$MESSAGE"
     fi
+  else
+    if [[ -z "$VOLUME_DELETE_ONLY_DRIVER" ]]; then
+      $DOCKER volume ls --filter "dangling=true" -q | grep -v -f $EXCLUDE_VOLUMES_IDS_FILE > volumes.reap || true
+    else
+      $DOCKER volume ls --filter "dangling=true" --filter "driver=$VOLUME_DELETE_ONLY_DRIVER" -q | grep -v -f $EXCLUDE_VOLUMES_IDS_FILE > volumes.reap || true
+    fi
+
+    if [[ $DRY_RUN -gt 0 ]]; then
+      volumes_log "The following volume would have been removed" volumes.reap
+    else
+      volumes_log "Removing volume" volumes.reap
+      xargs -n 1 $DOCKER volume rm < volumes.reap &>/dev/null || true
+    fi
+  fi
 fi
